version: "3"

services:
    app:
        env_file: .env
        build: "."
        ports:
            - "5000:5000"
        volumes:
            - "./data:/data"
        environment:
            DB_URI: "host=${POSTGRES_HOST} user=${POSTGRES_USER} dbname=${POSTGRES_DB} sslmode=disable password=${POSTGRES_PASSWORD}"
        depends_on:
            - db
    db:
        env_file: .env
        image: postgres
        restart: always
        volumes:
            - "./db:/var/lib/postgresql"
            - "./data:/data"
        ports:
            - "5432"
